SELECT
    ?personLabel ?nationalityLabel ?orcid ?twitter ?linkedin  ?gscholar ?github ?website
WHERE
{
    BIND(wd:@@@ qid @@@ AS ?person)
    ?person wdt:P496 ?orcid .
    ?person wdt:P2002 ?twitter .
    ?person wdt:P27 ?nationality .
    ?person wdt:P6634 ?linkedin .
    ?person wdt:P1960 ?gscholar .
    ?person wdt:P856 ?website .
    ?person wdt:P2037 ?github .
    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
