SELECT
    ?personLabel ?nationalityLabel ?orcid ?twitter ?linkedin ?gscholar ?github ?mastodon ?website
WHERE
{
    BIND(wd:@@@ qid @@@ AS ?person)
    ?person wdt:P496 ?orcid .
    OPTIONAL { ?person wdt:P2002 ?twitter . }
    OPTIONAL { ?person wdt:P27 ?nationality . }
    OPTIONAL { ?person wdt:P6634 ?linkedin . }
    OPTIONAL { ?person wdt:P1960 ?gscholar . }
    OPTIONAL { ?person wdt:P856 ?website . }
    OPTIONAL { ?person wdt:P2037 ?github . }
    OPTIONAL { ?person wdt:P4033 ?mastodon . }
    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
LIMIT 1
