SELECT
  ?institution ?institutionLabel ?degree ?degreeLabel ?start_date ?end_date ?country ?countryLabel ?thesis ?thesisLabel
WHERE
{
  wd:@@@ qid @@@ p:P69 ?statement .
  ?statement ps:P69 ?institution .
  ?institution wdt:P17 ?country .
  OPTIONAL { ?statement pq:P512 ?degree . }
  OPTIONAL { ?statement pq:P580 ?start_date . }
  OPTIONAL { ?statement pq:P582 ?end_date . }
  OPTIONAL { ?statement pq:P1026 ?thesis . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". } # Helps get the label in your language, if not, then en language
}
ORDER BY DESC(?start_date)
