SELECT
  ?employer ?employerLabel ?position ?positionLabel ?start_date ?end_date ?location ?locationLabel ?country ?countryLabel
WHERE
{
  wd:@@@ qid @@@ p:P108 ?statement .
  ?statement ps:P108 ?employer .
  OPTIONAL {
    ?statement pq:P276 ?location .
    ?location wdt:P17 ?country .
  }
  OPTIONAL { ?statement pq:P39 ?position . }
  OPTIONAL { ?statement pq:P580 ?start_date . }
  OPTIONAL { ?statement pq:P582 ?end_date . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } # Helps get the label in your language, if not, then en language
}
ORDER BY DESC(?start_date)
