SELECT
    ?work ?workLabel ?venue ?date ?arxiv ?doi ?pubmed ?biorxiv ?url ?pmc
WHERE {
    SERVICE wdsubgraph:scholarly_articles {
        ?work wdt:P50 wd:@@@ qid @@@ .
        OPTIONAL { ?work wdt:P1433 ?venue }
        OPTIONAL { ?work wdt:P577 ?date }
        OPTIONAL { ?work wdt:P818 ?arxiv }
        OPTIONAL { ?work wdt:P356 ?doi }
        OPTIONAL { ?work wdt:P698 ?pubmed }
        OPTIONAL { ?work wdt:P3951 ?biorxiv }
        OPTIONAL { ?work wdt:P953 ?url }
        OPTIONAL { ?work wdt:P932 ?pmc }
        OPTIONAL {
            ?work rdfs:label ?workLabel .
            FILTER(LANG(?workLabel) in ("en", "mul"))
        }
    }
}
